# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\curra\Google Drive\TFG\GUI\untitled\mainwindowinterface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 473)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rb_runmode = QtWidgets.QRadioButton(self.centralWidget)
        self.rb_runmode.setChecked(True)
        self.rb_runmode.setObjectName("rb_runmode")
        self.gridLayout_3.addWidget(self.rb_runmode, 0, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 7, 1, 1, 1)
        self.lineEdit_Y = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_Y.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Y.sizePolicy().hasHeightForWidth())
        self.lineEdit_Y.setSizePolicy(sizePolicy)
        self.lineEdit_Y.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.gridLayout_3.addWidget(self.lineEdit_Y, 6, 2, 1, 1)
        self.pushButton_Send = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Send.sizePolicy().hasHeightForWidth())
        self.pushButton_Send.setSizePolicy(sizePolicy)
        self.pushButton_Send.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.gridLayout_3.addWidget(self.pushButton_Send, 7, 2, 1, 1)
        self.lineEdit_X = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_X.sizePolicy().hasHeightForWidth())
        self.lineEdit_X.setSizePolicy(sizePolicy)
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.gridLayout_3.addWidget(self.lineEdit_X, 5, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 1, 1, 1)
        self.rb_trainmode = QtWidgets.QRadioButton(self.centralWidget)
        self.rb_trainmode.setObjectName("rb_trainmode")
        self.gridLayout_3.addWidget(self.rb_trainmode, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 1, 1, 1)
        self.comboBox_vehicle = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_vehicle.setObjectName("comboBox_vehicle")
        self.gridLayout_3.addWidget(self.comboBox_vehicle, 1, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.camera = QtWidgets.QVBoxLayout()
        self.camera.setSpacing(6)
        self.camera.setObjectName("camera")
        self.label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.camera.addWidget(self.label)
        self.gridLayout_2.addLayout(self.camera, 0, 0, 1, 1)
        self.group_logger = QtWidgets.QGroupBox(self.centralWidget)
        self.group_logger.setMaximumSize(QtCore.QSize(16777215, 200))
        self.group_logger.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.group_logger.setObjectName("group_logger")
        self.gridLayout = QtWidgets.QGridLayout(self.group_logger)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton = QtWidgets.QRadioButton(self.group_logger)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 2, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.group_logger)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 5, 0, 1, 7)
        self.radioButton_2 = QtWidgets.QRadioButton(self.group_logger)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 2, 3, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.group_logger)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 2, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(776, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 6, 3, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.group_logger)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 2, 5, 1, 1)
        self.gridLayout_2.addWidget(self.group_logger, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1060, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuArchivo = QtWidgets.QMenu(self.menuBar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAyuda = QtWidgets.QMenu(self.menuBar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionManual_de_utilizaci_n = QtWidgets.QAction(MainWindow)
        self.actionManual_de_utilizaci_n.setObjectName("actionManual_de_utilizaci_n")
        self.actionOpen_csv = QtWidgets.QAction(MainWindow)
        self.actionOpen_csv.setObjectName("actionOpen_csv")
        self.menuArchivo.addAction(self.actionOpen_csv)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionManual_de_utilizaci_n)
        self.menuAyuda.addAction(self.actionSobre)
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rb_runmode.setText(_translate("MainWindow", "Run mode"))
        self.checkBox_2.setText(_translate("MainWindow", "View path"))
        self.pushButton_Send.setText(_translate("MainWindow", "Send coordinates"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.checkBox.setText(_translate("MainWindow", "View cameras"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.rb_trainmode.setText(_translate("MainWindow", "Train mode"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "View"))
        self.group_logger.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioButton.setText(_translate("MainWindow", "Info"))
        self.radioButton_2.setText(_translate("MainWindow", "Warning"))
        self.radioButton_3.setText(_translate("MainWindow", "Error"))
        self.radioButton_4.setText(_translate("MainWindow", "Debug"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionSalir.setText(_translate("MainWindow", "Exit"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre..."))
        self.actionManual_de_utilizaci_n.setText(_translate("MainWindow", "Manual de utilización"))
        self.actionOpen_csv.setText(_translate("MainWindow", "Open .csv"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

