# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\curra\Google Drive\TFG\GUI\untitled\mainwindowinterface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 495)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CameraCheck = QtWidgets.QCheckBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CameraCheck.sizePolicy().hasHeightForWidth())
        self.CameraCheck.setSizePolicy(sizePolicy)
        self.CameraCheck.setObjectName("CameraCheck")
        self.horizontalLayout.addWidget(self.CameraCheck)
        self.PathCheck = QtWidgets.QCheckBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PathCheck.sizePolicy().hasHeightForWidth())
        self.PathCheck.setSizePolicy(sizePolicy)
        self.PathCheck.setObjectName("PathCheck")
        self.horizontalLayout.addWidget(self.PathCheck)
        self.gridLayout_2.addLayout(self.horizontalLayout, 9, 2, 1, 1)
        self.group_logger = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_logger.sizePolicy().hasHeightForWidth())
        self.group_logger.setSizePolicy(sizePolicy)
        self.group_logger.setMaximumSize(QtCore.QSize(16777215, 200))
        self.group_logger.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.group_logger.setObjectName("group_logger")
        self.gridLayout = QtWidgets.QGridLayout(self.group_logger)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.WarnCheck = QtWidgets.QRadioButton(self.group_logger)
        self.WarnCheck.setChecked(True)
        self.WarnCheck.setAutoExclusive(False)
        self.WarnCheck.setObjectName("WarnCheck")
        self.gridLayout.addWidget(self.WarnCheck, 1, 2, 1, 1)
        self.ErrorCheck = QtWidgets.QRadioButton(self.group_logger)
        self.ErrorCheck.setChecked(True)
        self.ErrorCheck.setAutoExclusive(False)
        self.ErrorCheck.setObjectName("ErrorCheck")
        self.gridLayout.addWidget(self.ErrorCheck, 1, 3, 1, 1)
        self.InfoCheck = QtWidgets.QRadioButton(self.group_logger)
        self.InfoCheck.setChecked(True)
        self.InfoCheck.setAutoExclusive(False)
        self.InfoCheck.setObjectName("InfoCheck")
        self.gridLayout.addWidget(self.InfoCheck, 1, 1, 1, 1)
        self.LoggerBrowser = QtWidgets.QTextBrowser(self.group_logger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoggerBrowser.sizePolicy().hasHeightForWidth())
        self.LoggerBrowser.setSizePolicy(sizePolicy)
        self.LoggerBrowser.setMaximumSize(QtCore.QSize(16777215, 120))
        self.LoggerBrowser.setObjectName("LoggerBrowser")
        self.gridLayout.addWidget(self.LoggerBrowser, 3, 0, 1, 7)
        self.DebugCheck = QtWidgets.QRadioButton(self.group_logger)
        self.DebugCheck.setAutoExclusive(False)
        self.DebugCheck.setObjectName("DebugCheck")
        self.gridLayout.addWidget(self.DebugCheck, 1, 5, 1, 1)
        self.gridLayout_2.addWidget(self.group_logger, 8, 2, 1, 1)
        self.camera = QtWidgets.QVBoxLayout()
        self.camera.setSpacing(6)
        self.camera.setObjectName("camera")
        self.label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.camera.addWidget(self.label)
        self.gridLayout_2.addLayout(self.camera, 0, 0, 13, 1)
        self.lineEdit_X = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_X.sizePolicy().hasHeightForWidth())
        self.lineEdit_X.setSizePolicy(sizePolicy)
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.gridLayout_2.addWidget(self.lineEdit_X, 10, 2, 1, 1)
        self.lineEdit_Y = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_Y.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Y.sizePolicy().hasHeightForWidth())
        self.lineEdit_Y.setSizePolicy(sizePolicy)
        self.lineEdit_Y.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.gridLayout_2.addWidget(self.lineEdit_Y, 11, 2, 1, 1)
        self.pushButton_Send = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Send.sizePolicy().hasHeightForWidth())
        self.pushButton_Send.setSizePolicy(sizePolicy)
        self.pushButton_Send.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.gridLayout_2.addWidget(self.pushButton_Send, 12, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.run_tab = QtWidgets.QWidget()
        self.run_tab.setObjectName("run_tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.run_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 271, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.tabWidget.addTab(self.run_tab, "")
        self.train_tab = QtWidgets.QWidget()
        self.train_tab.setObjectName("train_tab")
        self.tabWidget.addTab(self.train_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1107, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuArchivo = QtWidgets.QMenu(self.menuBar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAyuda = QtWidgets.QMenu(self.menuBar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_docs = QtWidgets.QAction(MainWindow)
        self.action_docs.setObjectName("action_docs")
        self.actionOpen_csv = QtWidgets.QAction(MainWindow)
        self.actionOpen_csv.setObjectName("actionOpen_csv")
        self.menuArchivo.addAction(self.actionOpen_csv)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.action_docs)
        self.menuAyuda.addAction(self.action_about)
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CameraCheck.setText(_translate("MainWindow", "View cameras"))
        self.PathCheck.setText(_translate("MainWindow", "View path"))
        self.group_logger.setTitle(_translate("MainWindow", "Logger"))
        self.WarnCheck.setText(_translate("MainWindow", "Warning"))
        self.ErrorCheck.setText(_translate("MainWindow", "Error"))
        self.InfoCheck.setText(_translate("MainWindow", "Info"))
        self.DebugCheck.setText(_translate("MainWindow", "Debug"))
        self.label.setText(_translate("MainWindow", "View"))
        self.pushButton_Send.setText(_translate("MainWindow", "Send coordinates"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.run_tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.train_tab), _translate("MainWindow", "Tab 2"))
        self.menuArchivo.setTitle(_translate("MainWindow", "File"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Help"))
        self.actionSalir.setText(_translate("MainWindow", "Exit"))
        self.action_about.setText(_translate("MainWindow", "About..."))
        self.action_docs.setText(_translate("MainWindow", "Manual de utilización"))
        self.actionOpen_csv.setText(_translate("MainWindow", "Open .csv"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

